#!/usr/bin/env bash
#
# build-summary-tree.sh — L2 hierarchical-summary skeleton for token-cheap GLOBAL questions.
#
# The research (docs/research/digital-colleague-kb.md) found that "global / sensemaking"
# questions over a huge codebase are answered cheapest by hierarchical summaries (RAPTOR /
# GraphRAG community summaries): read the top-level summary, drill down only where needed —
# instead of stuffing the repo into context. This tool builds the *tree structure + per-node
# factual rollup* (subtree file count + the most-referenced symbols under it) and leaves a
# `summary:` slot at each node for the generator agent to fill (the abstractive step needs an
# LLM; we never fabricate it). It reuses the L1 symbol index (build-symbol-index.sh).
#
# Read order for a consuming skill: global → subsystem (top dir) → module (subdir) → then
# `find-symbol.sh` / the anchor to the code. Token budget = depth x symbols-per-node.
#
# Usage:
#   build-summary-tree.sh <codebase> [out_dir] [depth] [syms_per_node]
#     out_dir default <codebase>/.docforge/summaries ; depth default 2 ; syms_per_node default 8
#
set -euo pipefail

CODE="${1:?usage: build-summary-tree.sh <codebase> [out_dir] [depth] [syms_per_node]}"
OUT="${2:-$CODE/.docforge/summaries}"
DEPTH="${3:-2}"
NSYM="${4:-8}"
HERE="$(cd "$(dirname "$0")" && pwd)"

command -v rg >/dev/null 2>&1 || { echo "build-summary-tree: need ripgrep (rg)" >&2; exit 2; }
mkdir -p "$OUT"

# Reuse (or build) the L1 symbol index next to the summaries.
SYM="$OUT/symbols"
if [ ! -f "$SYM/symbols.tsv" ]; then
  if command -v ctags >/dev/null 2>&1; then
    "$HERE/build-symbol-index.sh" "$CODE" "$SYM" 1000 >/dev/null 2>&1 || true
  fi
fi

python3 - "$CODE" "$OUT" "$DEPTH" "$NSYM" <<'PY'
import os, sys, subprocess, collections
code, out, depth, nsym = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4])
code = os.path.abspath(code)

# file list (git if available, else walk)
try:
    files = subprocess.check_output(["git","-C",code,"ls-files"], text=True).splitlines()
except Exception:
    files = []
    for r,_,fs in os.walk(code):
        if os.sep+".git" in r: continue
        for f in fs:
            files.append(os.path.relpath(os.path.join(r,f), code))

# global identifier frequency (centrality proxy)
freq = {}
fp = os.path.join(out, "symbols", "freq.txt")
if os.path.exists(fp):
    for line in open(fp, encoding="utf-8", errors="ignore"):
        c,_,n = line.strip().partition(" ")
        try: freq[n.strip()] = int(c.strip())
        except ValueError: pass

# code-kind symbols with their file
CODE_KINDS={"function","method","prototype","class","struct","interface","enum","union","typedef","macro","namespace","trait"}
sym_by_file = collections.defaultdict(list)
sp = os.path.join(out, "symbols", "symbols.tsv")
if os.path.exists(sp):
    for line in open(sp, encoding="utf-8", errors="ignore"):
        p = line.rstrip("\n").split("\t")
        if len(p) >= 3 and p[1] in CODE_KINDS:
            sym_by_file[p[2]].append((p[0], p[1]))

def node_key(path, d):
    parts = path.split("/")
    if len(parts) <= 1: return "(root)"
    return "/".join(parts[:d])

# build nodes per depth level 1..depth
levels = {}  # d -> {nodekey: {'files':int, 'syms':Counter of (name,kind)->freq}}
for d in range(1, depth+1):
    nodes = {}
    for f in files:
        k = node_key(f, d)
        n = nodes.setdefault(k, {"files":0, "syms":{}})
        n["files"] += 1
        for (name,kind) in sym_by_file.get(f, []):
            sc = freq.get(name, 0)
            cur = n["syms"].get(name)
            if cur is None or sc > cur[0]:
                n["syms"][name] = (sc, kind, f)
    levels[d] = nodes

def top_syms(node):
    items = sorted(node["syms"].items(), key=lambda x:-x[1][0])[:nsym]
    return [(n, k, os.path.relpath(os.path.abspath(os.path.join(code,fl)), code), sc) for n,(sc,k,fl) in items]

with open(os.path.join(out, "summary-tree.md"), "w") as f:
    f.write("# Summary Tree (L2) — read top-down, drill where needed\n\n")
    f.write("Hierarchical, token-budgeted map for **global questions**. Each node lists its "
            "subtree size + most-referenced symbols; fill each `summary:` (◐) with 1–2 lines. "
            "Drill: global → subsystem → module → `find-symbol.sh`. Generated by "
            "`build-summary-tree.sh`.\n\n")
    f.write(f"**Global:** {len(files)} files. summary: _(◐ TODO: what is this codebase, in 2 lines)_\n\n")
    # level 1 = subsystems (top dirs)
    l1 = sorted(levels[1].items(), key=lambda x:-x[1]["files"])
    for k, node in l1:
        f.write(f"## {k}/  — {node['files']} files\n")
        f.write("summary: _(◐ TODO: role of this subsystem, 1–2 lines)_\n\n")
        ts = top_syms(node)
        if ts:
            f.write("| symbol | kind | anchor | refs |\n|---|---|---|---|\n")
            for n,kd,an,sc in ts:
                f.write(f"| `{n}` | {kd} | `{an} → {n}` | {sc} |\n")
            f.write("\n")
        # level 2 = modules (subdirs under this top dir), if depth>=2
        if depth >= 2:
            subs = sorted([(kk,nn) for kk,nn in levels[2].items()
                           if kk.split("/")[0]==k and "/" in kk], key=lambda x:-x[1]["files"])[:8]
            for kk, nn in subs:
                f.write(f"### {kk}/  — {nn['files']} files\n")
                f.write("summary: _(◐ TODO: 1 line)_  ")
                tn = top_syms(nn)
                if tn:
                    f.write("top: " + ", ".join(f"`{n}`" for n,_,_,_ in tn[:5]))
                f.write("\n\n")

print(f"build-summary-tree: {len(files)} files; {len(levels[1])} subsystems; "
      f"depth {depth} → {out}/summary-tree.md")
PY
