#!/usr/bin/env bash
#
# build-symbol-index.sh — L1 structured-code index for fast, token-budgeted localization.
#
# Produces, for a codebase: (1) a symbol table of definitions (name/kind/file/scope) via
# universal-ctags, and (2) a token-budgeted "repo map" of the top-N symbols ranked by
# reference frequency (a cheap centrality proxy, Aider-repo-map style). This is the L1 layer
# from docs/research/digital-colleague-kb.md: give an agent a structured map so it can locate
# code precisely instead of stuffing the repo into context. Anchors are emitted as
# `file → symbol` (stable; no line numbers in the anchor).
#
# Upgrade path (richer, heavier): tree-sitter / LSP / SCIP / stack graphs for scope-accurate,
# cross-repo resolution. ctags is pattern-based (no semantic scope) but dependency-light.
#
# Usage:
#   build-symbol-index.sh <codebase> [out_dir] [top_n]
#     out_dir default: <codebase>/.docforge/symbols   top_n default: 200
#
set -euo pipefail

CODE="${1:?usage: build-symbol-index.sh <codebase> [out_dir] [top_n]}"
OUT="${2:-$CODE/.docforge/symbols}"
TOPN="${3:-200}"

command -v ctags >/dev/null 2>&1 || { echo "build-symbol-index: need universal-ctags on PATH" >&2; exit 2; }
command -v rg    >/dev/null 2>&1 || { echo "build-symbol-index: need ripgrep (rg) on PATH" >&2; exit 2; }
mkdir -p "$OUT"

# 1. Definitions (JSON lines) via ctags.
ctags --output-format=json --fields=+nKlS --extras=+q \
      -R -f - "$CODE" > "$OUT/tags.jsonl" 2>/dev/null || true

# 2. Global identifier frequency in one rg pass (centrality proxy; ids of length >= 3).
rg -oN --no-filename -g '!.git' '[A-Za-z_][A-Za-z0-9_]{2,}' "$CODE" 2>/dev/null \
  | sort | uniq -c | sort -rn > "$OUT/freq.txt" || true

# 3. Assemble symbols.tsv + ranked, budgeted repomap.md.
python3 - "$OUT" "$TOPN" "$CODE" <<'PY'
import json, os, sys
out, topn, code = sys.argv[1], int(sys.argv[2]), os.path.abspath(sys.argv[3])

freq = {}
fp = os.path.join(out, "freq.txt")
if os.path.exists(fp):
    for line in open(fp, encoding="utf-8", errors="ignore"):
        line = line.strip()
        if not line:
            continue
        c, _, name = line.partition(" ")
        try:
            freq[name.strip()] = int(c.strip())
        except ValueError:
            pass

defs = []
for line in open(os.path.join(out, "tags.jsonl"), encoding="utf-8", errors="ignore"):
    line = line.strip()
    if not line:
        continue
    try:
        t = json.loads(line)
    except ValueError:
        continue
    if t.get("_type") != "tag" or not t.get("name") or not t.get("path"):
        continue
    rel = os.path.relpath(os.path.abspath(t["path"]), code)
    defs.append((t["name"], t.get("kind", ""), rel, t.get("scope", "")))

with open(os.path.join(out, "symbols.tsv"), "w") as f:
    f.write("name\tkind\tfile\tscope\n")
    for n, k, r, s in sorted(defs):
        f.write(f"{n}\t{k}\t{r}\t{s}\n")

# Rank only "code-ish" definitions (functions, types, macros) for the repo map; data-file
# tags (JSON string/object keys, Make targets, struct members) are kept in symbols.tsv but
# would otherwise drown the map.
CODE_KINDS = {"function", "method", "prototype", "class", "struct", "interface",
              "enum", "enumerator", "union", "typedef", "macro", "namespace", "trait"}
best = {}
for n, k, r, s in defs:
    if k not in CODE_KINDS:
        continue
    score = freq.get(n, 0)
    if n not in best or score > best[n][0]:
        best[n] = (score, k, r, s)
ranked = sorted(best.items(), key=lambda x: -x[1][0])[:topn]

with open(os.path.join(out, "repomap.md"), "w") as f:
    f.write(f"# Repo Map — top {len(ranked)} symbols by reference frequency\n\n")
    f.write("Generated by `build-symbol-index.sh`. Anchors are `file → symbol` (stable).\n\n")
    f.write("| # | refs | symbol | kind | anchor |\n|---|---|---|---|---|\n")
    for i, (n, (sc, k, r, s)) in enumerate(ranked, 1):
        f.write(f"| {i} | {sc} | `{n}` | {k} | `{r} → {n}` |\n")

print(f"build-symbol-index: {len(defs)} definitions, {len(best)} unique symbols; "
      f"repo map top {len(ranked)} → {out}/repomap.md")
PY
